### ISSUE TITLE
No value for FLUSH_TOILET in Mustang TOILET_TYPE total

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/census-data#10]
@studenton 

The [Mustang TOILET_TYPE.csv](https://github.com/Code4Nepal/census-data/blob/master/districts/Mustang/TOILET_TYPE.csv) is missing the total for FLUSH_TOILET, but the VDCs have flush toilet totals.

Do you have a script that can correct this?

**Comment by amitness** [comment]
The total is 1382. Seems some error occurred during extraction from PDF for this district. All other districts have the totals.

**Comment by amitness** [comment]
Thanks for pointing out. I'll fix it in the census-data repo as well.
