### ISSUE TITLE
different district names between districts_complete.csv and district.geojson

### ISSUE THREAD

**Issue by individual-it** [Code4Nepal/census-data#14]
I'm trying to combine the data from districts_complete.csv and the district.geojson from https://github.com/Code4Nepal/nepalmap_app/blob/dev/wazimap_np/static/geo/district.geojson

comparing the list of district names in both files gives me this diff:

```
< "19","DHANUSHA"
---
> "19","DHANUSA"
27c27
< "26","ILLAM"
---
> "26","ILAM"
37c37
< "36","KAVRE"
---
> "36","KAVREPALANCHOK"
42c42
< "41","MAKAWANPUR"
---
> "41","MAKWANPUR"
67c67
< "66","SINDHUPALCHOWK"
---
> "66","SINDHUPALCHOK"
73,75c73,76
< "72","TAPLEJUNG"
< "73","TEHRATHUM"
< "74","UDAYAPUR"
---
> "72","TANAHU"
> "73","TAPLEJUNG"
> "74","TEHRATHUM"
> "75","UDAYAPUR"
```

So some names are typed different and "TANAHU" missing altogether in the CSV file

**Comment by cliftonmcintosh** [comment]
@individual-it 

I don't believe `districts_complete.csv` has been used at all in NepalMap. Tanahu has data in NepalMap. That was derived from the CSVs in [the Tahanun directory](https://github.com/Code4Nepal/census-data/tree/master/districts) in the census-data project.

It's true that the names in the geo file sometimes differ from the names in the census-data project. The geo file and the census files have two different data sources, and we have done our best to try to match them. If there are discrepancies that should be corrected, please let us know.

[Here is Tanahu](http://www.nepalmap.org/profiles/district-38-tanahu/) in NepalMap.

What is your goal? If you can explain what you are looking for, perhaps @studenton or one of the other people here can help.

**Comment by individual-it** [comment]
I need to create a heat-map of deaf in Nepal for a research I'm helping with. Here where I'm up to:
![rplot12](https://cloud.githubusercontent.com/assets/2425577/21874562/bc622d3c-d89d-11e6-918a-638ab8e2fdb3.png)
I use R for that whole research, so I'm doing this map also with R

as the nepal-map project has nice geojson data the idea was to use that and then combine by district names to the CSV data. When trying to do that I found the problem of the different names and also #13 
Finally I went back yesterday and got all data from nepal-map, placed the sql files in psql and exported them into CSV, so I have a static file to do the analysis. So actually I achieved my goal but the problem persists.

I assumed districts_complete.csv is just a sum of all the smaller district CSVs. Is that not meant to be?
What is the "correct" data? SQL files in napal-map repro? district CSVs? districts_complete.csv?
If its not districts_complete.csv, shouldn't we try to generate a new districts_complete.csv from the correct data?

**Comment by cliftonmcintosh** [comment]
@individual-it 

I'm not sure what counts as correct. In working through different data sets, we have found that there are often discrepancies in how the names are spelled in English. In fact, @studenton spent a lot of time mapping village and municipality names between our census data and our NepalMap geo data. He deserves a lot of credit for our ability to present data at the VDC level.

For NepalMap, I did the mappings for district names, and I found it easiest to use the names in the geo-data files and then map those to the names of the [district directories in the census-data project](https://github.com/Code4Nepal/census-data/tree/master/districts).

Perhaps Amit (@studenton) would have an idea of whether or not he feels it would be valuable to update the `districts_complete.csv` file.

**Comment by amitness** [comment]
Yes, @individual-it . Data released by the government use a different names for districts than that used by OpenStreetMap on which the geojson is based. We'd to deal with this problem as well. To solve that, we used a mapping between the names.

```
< "19","DHANUSHA"
---
> "19","DHANUSA"
```

The mapping for VDC is present as a JSON [here](https://github.com/Code4Nepal/geo/blob/master/vdc_geo_code_mappings.json).

Here's the relevant [issue](https://github.com/Code4Nepal/maptools/issues/11) that discusses on it.

**Comment by amitness** [comment]
The separate district CSVs would be the best source for "correct" data.

**Comment by individual-it** [comment]
so what we could do is to merge all separate districts into one CSV and maybe add a special column for alternative names. Are you interested in such a PR?

**Comment by amitness** [comment]
@individual-it Sure.

**Comment by individual-it** [comment]
added a PR #15 a while ago.
Any interest in it?

**Comment by amitness** [comment]
@individual-it Thank you for the PR. I'll merge it.
