### ISSUE TITLE
What is the age range for the POPULATION_EDUCATION_LEVEL_PASSED.csv

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/census-data#5]
@studenton

Is it all ages? Adults? Aged X and over?

**Comment by ravinepal** [comment]
@cliftonmcintosh it's aged 5 years & above. Here's a related Google doc:  https://docs.google.com/spreadsheets/d/1CSpbdjrpx7Xem3q9Adtke91gtTePU_8tKcLJRnIS0qQ/edit?usp=sharing

**Comment by cliftonmcintosh** [comment]
Thanks.
